//! Interface localization for GridCraft: [Fluent](https://projectfluent.org) messages, command
//! labels, ribbon names, function documentation and keyboard shortcuts per language.
//!
//! The message files live in `locales/<tag>/` at the repository root and are embedded at build
//! time (`build.rs` + `include_str!`, so this works on wasm). `en-US` is the reference and the
//! fallback: a key missing in the active language is looked up in `en-US`, and a key missing there
//! is returned as is. Isolating marks are off, so rendered text has no bidi control characters.
//!
//! # Files and key scheme
//!
//! Every `*.ftl` file of a language is merged into one bundle, so a key must be unique across the
//! files of a language.
//!
//! | File | Keys |
//! |---|---|
//! | `commands.ftl` | `cmd-<id>-label`: engine command id with `.` replaced by `-` (`file.saveAs` → `cmd-file-saveAs-label`) |
//! | `ribbon.ftl` | `ribbon-tab-<slug>`, `ribbon-group-<slug>`: `slug` = lower-case ASCII letters and digits of the English name, other runs replaced by one `-` (`Page Layout` → `page-layout`, `Find & Select` → `find-select`) |
//! | `functions.ftl` | `fn-<NAME>` with `.` replaced by `-` (`BETA.DIST` → `fn-BETA-DIST`): value = short description, attribute `.args` = the parameter list as in the signature (optional parameters in `[ ]`, `...` for repetition, items separated by `, `); functions without parameters have no `.args` |
//! | `errors.ftl` | `error-<code>`, mirroring the engine error variants: `unknown-command` (`$command`), `command-disabled` (`$command`, `$reason`), `bad-params` (`$command`, `$message`), `no-document`, `internal` (`$command`, `$message`), `other` (`$message`) |
//! | `ui.ftl` and any other `*.ftl` | free-form keys owned by the code that uses them |
//! | `keymap.toml` | `[shortcuts."<command id>"]` entries, see [`Localizer::shortcut`] |
//!
//! A test requires every language to define exactly the keys, attributes and variables of
//! `en-US`, and every shortcut to name an existing command.
#![deny(clippy::unwrap_used, clippy::expect_used, clippy::panic, clippy::unimplemented, clippy::todo, clippy::unreachable)]
#![forbid(unsafe_code)]

use std::borrow::Cow;
use std::collections::BTreeMap;
use std::sync::OnceLock;

use fluent_bundle::concurrent::FluentBundle;
use fluent_bundle::{FluentArgs, FluentResource, FluentValue};
use serde::Deserialize;
use unic_langid::LanguageIdentifier;

/// Tag of the reference and fallback language.
pub const FALLBACK_TAG: &str = "en-US";

/// One embedded language directory, generated by `build.rs`.
struct LangSource {
    tag: &'static str,
    /// (file stem, contents) of every `*.ftl` file.
    files: &'static [(&'static str, &'static str)],
    /// Contents of `keymap.toml`, empty when absent.
    keymap: &'static str,
}

include!(concat!(env!("OUT_DIR"), "/langs.rs"));

static CELLS: [OnceLock<LangData>; LANG_COUNT] = [const { OnceLock::new() }; LANG_COUNT];

/// Keyboard layout family of a shortcut.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Platform {
    /// Windows and Linux: `Cmd` in a chord means Ctrl.
    Pc,
    /// macOS: `Cmd` in a chord means the Command key.
    Mac,
}

/// A value passed to a message variable.
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum Arg<'a> {
    Str(&'a str),
    Num(f64),
}

impl<'a> From<&'a str> for Arg<'a> {
    fn from(s: &'a str) -> Self {
        Arg::Str(s)
    }
}
impl<'a> From<&'a String> for Arg<'a> {
    fn from(s: &'a String) -> Self {
        Arg::Str(s)
    }
}
impl From<f64> for Arg<'_> {
    fn from(n: f64) -> Self {
        Arg::Num(n)
    }
}
impl From<i32> for Arg<'_> {
    fn from(n: i32) -> Self {
        Arg::Num(f64::from(n))
    }
}
impl From<u32> for Arg<'_> {
    fn from(n: u32) -> Self {
        Arg::Num(f64::from(n))
    }
}
impl From<i64> for Arg<'_> {
    fn from(n: i64) -> Self {
        Arg::Num(n as f64)
    }
}
impl From<usize> for Arg<'_> {
    fn from(n: usize) -> Self {
        Arg::Num(n as f64)
    }
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct KeymapFile {
    #[serde(default)]
    shortcuts: BTreeMap<String, ShortcutEntry>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct ShortcutEntry {
    keys: String,
    #[serde(default)]
    mac: Option<String>,
    /// Provenance of the entry (required: every shortcut says where it comes from).
    source: String,
}

/// A parsed language: its Fluent bundle and keymap.
struct LangData {
    tag: &'static str,
    bundle: FluentBundle<FluentResource>,
    shortcuts: BTreeMap<String, ShortcutEntry>,
    /// Syntax errors, key collisions and keymap errors found while loading (empty when healthy).
    problems: Vec<String>,
}

fn load(source: &'static LangSource) -> LangData {
    let mut problems = Vec::new();
    let id: LanguageIdentifier = source.tag.parse().unwrap_or_default();
    let mut bundle = FluentBundle::new_concurrent(vec![id]);
    bundle.set_use_isolating(false);
    for (name, text) in source.files {
        let resource = match FluentResource::try_new((*text).to_string()) {
            Ok(r) => r,
            Err((r, errors)) => {
                problems.push(format!("{}/{name}.ftl: {} syntax error(s)", source.tag, errors.len()));
                r
            }
        };
        if let Err(errors) = bundle.add_resource(resource) {
            problems.push(format!("{}/{name}.ftl: {} key(s) already defined in another file", source.tag, errors.len()));
        }
    }
    let shortcuts = match toml::from_str::<KeymapFile>(source.keymap) {
        Ok(k) => k.shortcuts,
        Err(e) => {
            problems.push(format!("{}/keymap.toml: {e}", source.tag));
            BTreeMap::new()
        }
    };
    LangData { tag: source.tag, bundle, shortcuts, problems }
}

fn lang(index: usize) -> Option<&'static LangData> {
    let source = LANGS.get(index)?;
    Some(CELLS.get(index)?.get_or_init(|| load(source)))
}

fn fallback_index() -> usize {
    LANGS.iter().position(|l| l.tag == FALLBACK_TAG).unwrap_or(0)
}

/// Tags of the languages that have a translation, `en-US` first-class like the others.
pub fn available_languages() -> Vec<&'static str> {
    LANGS.iter().map(|l| l.tag).collect()
}

/// Looks messages up for one language, falling back to `en-US`.
///
/// Cheap to create and copy: the parsed bundles are shared and built on first use.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Localizer {
    primary: usize,
    fallback: usize,
}

impl Default for Localizer {
    fn default() -> Self {
        Self::new(FALLBACK_TAG)
    }
}

impl Localizer {
    /// Negotiates `tag` (`pt-BR`, `pt_BR.UTF-8`, `pt`, `pt-AO`, `zh-HK`, `de-AT`, ...) against the
    /// languages that have a translation with [`gridcraft_locale::negotiate_index`], the rule the
    /// formula language and region use; an unknown or empty tag gives `en-US`.
    pub fn new(tag: &str) -> Localizer {
        let fallback = fallback_index();
        let primary = gridcraft_locale::negotiate_index(tag, &LANGS, |l: &LangSource| l.tag).unwrap_or(fallback);
        Localizer { primary, fallback }
    }

    /// Tag of the language in use (`en-US` when the requested one is not translated).
    pub fn tag(&self) -> &'static str {
        lang(self.primary).map_or(FALLBACK_TAG, |l| l.tag)
    }

    /// Message `key`, formatted with `args`. A key missing in the language comes from `en-US`, and a
    /// key missing there is returned unchanged, so a typo shows up on screen instead of failing.
    pub fn text(&self, key: &str, args: &[(&str, Arg<'_>)]) -> Cow<'static, str> {
        self.lookup(key, None, args).unwrap_or_else(|| Cow::Owned(key.to_string()))
    }

    /// Message `key` without variables.
    pub fn plain(&self, key: &str) -> Cow<'static, str> {
        self.text(key, &[])
    }

    /// Like [`Localizer::text`], but `None` when no language defines `key`.
    pub fn get(&self, key: &str, args: &[(&str, Arg<'_>)]) -> Option<Cow<'static, str>> {
        self.lookup(key, None, args)
    }

    /// Attribute `attr` of message `key` (`fn-SUM` / `args`), with the same fallback as [`Localizer::text`].
    pub fn attribute(&self, key: &str, attr: &str) -> Option<Cow<'static, str>> {
        self.lookup(key, Some(attr), &[])
    }

    /// Whether `en-US` or the active language defines `key`.
    pub fn has(&self, key: &str) -> bool {
        self.get(key, &[]).is_some()
    }

    fn lookup(&self, key: &str, attr: Option<&str>, args: &[(&str, Arg<'_>)]) -> Option<Cow<'static, str>> {
        let mut fluent_args = FluentArgs::new();
        for (name, value) in args {
            match value {
                Arg::Str(s) => fluent_args.set(*name, FluentValue::from((*s).to_string())),
                Arg::Num(n) => fluent_args.set(*name, FluentValue::from(*n)),
            }
        }
        for index in [self.primary, self.fallback] {
            let Some(data) = lang(index) else { continue };
            let Some(message) = data.bundle.get_message(key) else { continue };
            let pattern = match attr {
                Some(a) => message.get_attribute(a).map(|a| a.value()),
                None => message.value(),
            };
            let Some(pattern) = pattern else { continue };
            let mut errors = Vec::new();
            if args.is_empty() {
                return Some(data.bundle.format_pattern(pattern, None, &mut errors));
            }
            return Some(Cow::Owned(data.bundle.format_pattern(pattern, Some(&fluent_args), &mut errors).into_owned()));
        }
        None
    }

    /// Label of the engine command `id` (`file.saveAs`), or `None` for an unknown id.
    pub fn command_label(&self, id: &str) -> Option<Cow<'static, str>> {
        self.get(&command_key(id), &[])
    }

    /// Name of a ribbon tab given its English name (`Page Layout`).
    pub fn ribbon_tab(&self, english: &str) -> Option<Cow<'static, str>> {
        self.get(&format!("ribbon-tab-{}", slug(english)), &[])
    }

    /// Name of a ribbon group given its English name (`Find & Select`).
    pub fn ribbon_group(&self, english: &str) -> Option<Cow<'static, str>> {
        self.get(&format!("ribbon-group-{}", slug(english)), &[])
    }

    /// Short description of the function with canonical (English) name `name`.
    pub fn function_description(&self, name: &str) -> Option<Cow<'static, str>> {
        self.get(&function_key(name), &[])
    }

    /// Parameters of the function with canonical name `name`, in signature order, split with
    /// [`split_args`]: an optional group keeps its brackets as one item (`[default, result2]`,
    /// `[parameter1, ...]`) and repetition is `...`. Empty for functions without parameters.
    pub fn function_args(&self, name: &str) -> Vec<String> {
        self.attribute(&function_key(name), "args").map(|list| split_args(&list)).unwrap_or_default()
    }

    /// Message for an engine error `code` (`bad-params`), formatted with `args`.
    pub fn error(&self, code: &str, args: &[(&str, Arg<'_>)]) -> Option<Cow<'static, str>> {
        self.get(&format!("error-{code}"), args)
    }

    /// Shortcut chord of `command_id` for the PC layout; see [`Localizer::shortcut_for`].
    pub fn shortcut(&self, command_id: &str) -> Option<&'static str> {
        self.shortcut_for(command_id, Platform::Pc)
    }

    /// Shortcut chord of `command_id` on `platform`: the active language's keymap entry, else the
    /// `en-US` one. A chord is modifiers joined by `+` and a final key (`Cmd+Shift+S`, `F2`); `Cmd`
    /// is the platform command modifier, see [`Platform`].
    pub fn shortcut_for(&self, command_id: &str, platform: Platform) -> Option<&'static str> {
        [self.primary, self.fallback].into_iter().filter_map(lang).find_map(|data| {
            let entry = data.shortcuts.get(command_id)?;
            Some(match platform {
                Platform::Mac => entry.mac.as_deref().unwrap_or(&entry.keys),
                Platform::Pc => entry.keys.as_str(),
            })
        })
    }

    /// Provenance recorded in the keymap for the entry that [`Localizer::shortcut`] returns.
    pub fn shortcut_source(&self, command_id: &str) -> Option<&'static str> {
        [self.primary, self.fallback].into_iter().filter_map(lang).find_map(|data| data.shortcuts.get(command_id).map(|e| e.source.as_str()))
    }

    /// Every shortcut in effect (the language's entries over the `en-US` ones) as
    /// `(command id, chord)`, sorted by command id.
    pub fn shortcuts(&self, platform: Platform) -> Vec<(&'static str, &'static str)> {
        let mut ids: Vec<&'static str> = Vec::new();
        for data in [self.primary, self.fallback].into_iter().filter_map(lang) {
            ids.extend(data.shortcuts.keys().map(String::as_str));
        }
        ids.sort_unstable();
        ids.dedup();
        ids.into_iter().filter_map(|id| Some((id, self.shortcut_for(id, platform)?))).collect()
    }
}

/// Key of the label of engine command `id`.
pub fn command_key(id: &str) -> String {
    format!("cmd-{}-label", id.replace('.', "-"))
}

/// Key of the documentation of the function with canonical name `name`.
pub fn function_key(name: &str) -> String {
    format!("fn-{}", name.replace('.', "-"))
}

/// Slug of an English ribbon tab or group name: lower-case ASCII letters and digits, every other
/// run of characters replaced by a single `-`, no leading or trailing `-`.
pub fn slug(english: &str) -> String {
    let mut out = String::with_capacity(english.len());
    let mut pending = false;
    for c in english.chars() {
        if c.is_ascii_alphanumeric() {
            if pending && !out.is_empty() {
                out.push('-');
            }
            pending = false;
            out.push(c.to_ascii_lowercase());
        } else {
            pending = true;
        }
    }
    out
}

/// Splits the `.args` text of a function into top-level parameters: items are separated by commas
/// that are outside `[ ]`, and each item is trimmed, so a grouped optional part such as
/// `[default_or_value2, result2]` stays one item.
pub fn split_args(list: &str) -> Vec<String> {
    let mut items = Vec::new();
    let mut current = String::new();
    let mut depth = 0usize;
    for c in list.chars() {
        match c {
            '[' => depth += 1,
            ']' => depth = depth.saturating_sub(1),
            ',' if depth == 0 => {
                items.push(std::mem::take(&mut current));
                continue;
            }
            _ => {}
        }
        current.push(c);
    }
    items.push(current);
    items.into_iter().map(|s| s.trim().to_string()).filter(|s| !s.is_empty()).collect()
}

/// Problems found while loading the embedded files of every language (syntax errors, keys defined
/// in two files, an invalid `keymap.toml`), as `<tag>/<file>: <message>`. Empty when healthy; the
/// loader keeps whatever parsed, so a problem degrades text instead of failing.
pub fn load_problems() -> Vec<String> {
    (0..LANG_COUNT).filter_map(lang).flat_map(|l| l.problems.iter().cloned()).collect()
}

#[cfg(test)]
mod tests;
