//! The canonical names of every built-in worksheet function and the prefix files store them with.
//!
//! This is the single list the rest of the workspace derives from: the evaluator checks it against
//! the function registry and its own special forms, the locale data must translate every entry,
//! and the XLSX writer takes the `_xlfn.` / `_xlfn._xlws.` prefixes from it.

/// `(canonical name, file prefix)`, sorted by name. The prefix is `""`, `"_xlfn."` (functions
/// introduced after Excel 2007) or `"_xlfn._xlws."` (worksheet-only dynamic-array functions).
pub static BUILTINS: &[(&str, &str)] = &[
    ("ABS", ""),
    ("ACCRINT", ""),
    ("ACCRINTM", ""),
    ("ACOS", ""),
    ("ACOSH", ""),
    ("ACOT", "_xlfn."),
    ("ACOTH", "_xlfn."),
    ("ADDRESS", ""),
    ("AGGREGATE", "_xlfn."),
    ("AMORDEGRC", ""),
    ("AMORLINC", ""),
    ("AND", ""),
    ("ARABIC", "_xlfn."),
    ("AREAS", ""),
    ("ARRAYTOTEXT", "_xlfn."),
    ("ASC", ""),
    ("ASIN", ""),
    ("ASINH", ""),
    ("ATAN", ""),
    ("ATAN2", ""),
    ("ATANH", ""),
    ("AVEDEV", ""),
    ("AVERAGE", ""),
    ("AVERAGEA", ""),
    ("AVERAGEIF", ""),
    ("AVERAGEIFS", ""),
    ("BASE", "_xlfn."),
    ("BESSELI", ""),
    ("BESSELJ", ""),
    ("BESSELK", ""),
    ("BESSELY", ""),
    ("BETA.DIST", "_xlfn."),
    ("BETA.INV", "_xlfn."),
    ("BETADIST", ""),
    ("BETAINV", ""),
    ("BIN2DEC", ""),
    ("BIN2HEX", ""),
    ("BIN2OCT", ""),
    ("BINOM.DIST", "_xlfn."),
    ("BINOM.DIST.RANGE", "_xlfn."),
    ("BINOM.INV", "_xlfn."),
    ("BINOMDIST", ""),
    ("BITAND", "_xlfn."),
    ("BITLSHIFT", "_xlfn."),
    ("BITOR", "_xlfn."),
    ("BITRSHIFT", "_xlfn."),
    ("BITXOR", "_xlfn."),
    ("BYCOL", "_xlfn."),
    ("BYROW", "_xlfn."),
    ("CEILING", ""),
    ("CEILING.MATH", "_xlfn."),
    ("CEILING.PRECISE", "_xlfn."),
    ("CELL", ""),
    ("CHAR", ""),
    ("CHIDIST", ""),
    ("CHIINV", ""),
    ("CHISQ.DIST", "_xlfn."),
    ("CHISQ.DIST.RT", "_xlfn."),
    ("CHISQ.INV", "_xlfn."),
    ("CHISQ.INV.RT", "_xlfn."),
    ("CHISQ.TEST", "_xlfn."),
    ("CHITEST", ""),
    ("CHOOSE", ""),
    ("CHOOSECOLS", "_xlfn."),
    ("CHOOSEROWS", "_xlfn."),
    ("CLEAN", ""),
    ("CODE", ""),
    ("COLUMN", ""),
    ("COLUMNS", ""),
    ("COMBIN", ""),
    ("COMBINA", "_xlfn."),
    ("COMPLEX", ""),
    ("CONCAT", "_xlfn."),
    ("CONCATENATE", ""),
    ("CONFIDENCE", ""),
    ("CONFIDENCE.NORM", "_xlfn."),
    ("CONFIDENCE.T", "_xlfn."),
    ("CONVERT", ""),
    ("CORREL", ""),
    ("COS", ""),
    ("COSH", ""),
    ("COT", "_xlfn."),
    ("COTH", "_xlfn."),
    ("COUNT", ""),
    ("COUNTA", ""),
    ("COUNTBLANK", ""),
    ("COUNTIF", ""),
    ("COUNTIFS", ""),
    ("COUPDAYBS", ""),
    ("COUPDAYS", ""),
    ("COUPDAYSNC", ""),
    ("COUPNCD", ""),
    ("COUPNUM", ""),
    ("COUPPCD", ""),
    ("COVAR", ""),
    ("COVARIANCE.P", "_xlfn."),
    ("COVARIANCE.S", "_xlfn."),
    ("CRITBINOM", ""),
    ("CSC", "_xlfn."),
    ("CSCH", "_xlfn."),
    ("CUBEKPIMEMBER", ""),
    ("CUBEMEMBER", ""),
    ("CUBEMEMBERPROPERTY", ""),
    ("CUBERANKEDMEMBER", ""),
    ("CUBESET", ""),
    ("CUBESETCOUNT", ""),
    ("CUBEVALUE", ""),
    ("CUMIPMT", ""),
    ("CUMPRINC", ""),
    ("DATE", ""),
    ("DATEDIF", ""),
    ("DATEVALUE", ""),
    ("DAVERAGE", ""),
    ("DAY", ""),
    ("DAYS", "_xlfn."),
    ("DAYS360", ""),
    ("DB", ""),
    ("DBCS", ""),
    ("DCOUNT", ""),
    ("DCOUNTA", ""),
    ("DDB", ""),
    ("DEC2BIN", ""),
    ("DEC2HEX", ""),
    ("DEC2OCT", ""),
    ("DECIMAL", "_xlfn."),
    ("DEGREES", ""),
    ("DELTA", ""),
    ("DEVSQ", ""),
    ("DGET", ""),
    ("DISC", ""),
    ("DMAX", ""),
    ("DMIN", ""),
    ("DOLLAR", ""),
    ("DOLLARDE", ""),
    ("DOLLARFR", ""),
    ("DPRODUCT", ""),
    ("DROP", "_xlfn."),
    ("DSTDEV", ""),
    ("DSTDEVP", ""),
    ("DSUM", ""),
    ("DURATION", ""),
    ("DVAR", ""),
    ("DVARP", ""),
    ("EDATE", ""),
    ("EFFECT", ""),
    ("ENCODEURL", "_xlfn."),
    ("EOMONTH", ""),
    ("ERF", ""),
    ("ERF.PRECISE", "_xlfn."),
    ("ERFC", ""),
    ("ERFC.PRECISE", "_xlfn."),
    ("ERROR.TYPE", ""),
    ("EVEN", ""),
    ("EXACT", ""),
    ("EXP", ""),
    ("EXPAND", "_xlfn."),
    ("EXPON.DIST", "_xlfn."),
    ("EXPONDIST", ""),
    ("F.DIST", "_xlfn."),
    ("F.DIST.RT", "_xlfn."),
    ("F.INV", "_xlfn."),
    ("F.INV.RT", "_xlfn."),
    ("F.TEST", "_xlfn."),
    ("FACT", ""),
    ("FACTDOUBLE", ""),
    ("FALSE", ""),
    ("FDIST", ""),
    ("FILTER", "_xlfn._xlws."),
    ("FILTERXML", "_xlfn."),
    ("FIND", ""),
    ("FINDB", ""),
    ("FINV", ""),
    ("FISHER", ""),
    ("FISHERINV", ""),
    ("FIXED", ""),
    ("FLOOR", ""),
    ("FLOOR.MATH", "_xlfn."),
    ("FLOOR.PRECISE", "_xlfn."),
    ("FORECAST", ""),
    ("FORECAST.LINEAR", "_xlfn."),
    ("FORMULATEXT", "_xlfn."),
    ("FREQUENCY", ""),
    ("FTEST", ""),
    ("FV", ""),
    ("FVSCHEDULE", ""),
    ("GAMMA", "_xlfn."),
    ("GAMMA.DIST", "_xlfn."),
    ("GAMMA.INV", "_xlfn."),
    ("GAMMADIST", ""),
    ("GAMMAINV", ""),
    ("GAMMALN", ""),
    ("GAMMALN.PRECISE", "_xlfn."),
    ("GAUSS", "_xlfn."),
    ("GCD", ""),
    ("GEOMEAN", ""),
    ("GESTEP", ""),
    ("GROUPBY", "_xlfn."),
    ("GROWTH", ""),
    ("HARMEAN", ""),
    ("HEX2BIN", ""),
    ("HEX2DEC", ""),
    ("HEX2OCT", ""),
    ("HLOOKUP", ""),
    ("HOUR", ""),
    ("HSTACK", "_xlfn."),
    ("HYPERLINK", ""),
    ("HYPGEOM.DIST", "_xlfn."),
    ("HYPGEOMDIST", ""),
    ("IF", ""),
    ("IFERROR", ""),
    ("IFNA", "_xlfn."),
    ("IFS", "_xlfn."),
    ("IMABS", ""),
    ("IMAGINARY", ""),
    ("IMARGUMENT", ""),
    ("IMCONJUGATE", ""),
    ("IMCOS", ""),
    ("IMCOSH", "_xlfn."),
    ("IMCOT", "_xlfn."),
    ("IMCSC", "_xlfn."),
    ("IMCSCH", "_xlfn."),
    ("IMDIV", ""),
    ("IMEXP", ""),
    ("IMLN", ""),
    ("IMLOG10", ""),
    ("IMLOG2", ""),
    ("IMPOWER", ""),
    ("IMPRODUCT", ""),
    ("IMREAL", ""),
    ("IMSEC", "_xlfn."),
    ("IMSECH", "_xlfn."),
    ("IMSIN", ""),
    ("IMSINH", "_xlfn."),
    ("IMSQRT", ""),
    ("IMSUB", ""),
    ("IMSUM", ""),
    ("IMTAN", "_xlfn."),
    ("INDEX", ""),
    ("INDIRECT", ""),
    ("INFO", ""),
    ("INT", ""),
    ("INTERCEPT", ""),
    ("INTRATE", ""),
    ("IPMT", ""),
    ("IRR", ""),
    ("ISBLANK", ""),
    ("ISERR", ""),
    ("ISERROR", ""),
    ("ISEVEN", ""),
    ("ISFORMULA", "_xlfn."),
    ("ISLOGICAL", ""),
    ("ISNA", ""),
    ("ISNONTEXT", ""),
    ("ISNUMBER", ""),
    ("ISO.CEILING", ""),
    ("ISODD", ""),
    ("ISOMITTED", "_xlfn."),
    ("ISOWEEKNUM", "_xlfn."),
    ("ISPMT", ""),
    ("ISREF", ""),
    ("ISTEXT", ""),
    ("JIS", ""),
    ("KURT", ""),
    ("LAMBDA", "_xlfn."),
    ("LARGE", ""),
    ("LCM", ""),
    ("LEFT", ""),
    ("LEFTB", ""),
    ("LEN", ""),
    ("LENB", ""),
    ("LET", "_xlfn."),
    ("LINEST", ""),
    ("LN", ""),
    ("LOG", ""),
    ("LOG10", ""),
    ("LOGEST", ""),
    ("LOGINV", ""),
    ("LOGNORM.DIST", "_xlfn."),
    ("LOGNORM.INV", "_xlfn."),
    ("LOGNORMDIST", ""),
    ("LOOKUP", ""),
    ("LOWER", ""),
    ("MAKEARRAY", "_xlfn."),
    ("MAP", "_xlfn."),
    ("MATCH", ""),
    ("MAX", ""),
    ("MAXA", ""),
    ("MAXIFS", "_xlfn."),
    ("MDETERM", ""),
    ("MDURATION", ""),
    ("MEDIAN", ""),
    ("MID", ""),
    ("MIDB", ""),
    ("MIN", ""),
    ("MINA", ""),
    ("MINIFS", "_xlfn."),
    ("MINUTE", ""),
    ("MINVERSE", ""),
    ("MIRR", ""),
    ("MMULT", ""),
    ("MOD", ""),
    ("MODE", ""),
    ("MODE.MULT", "_xlfn."),
    ("MODE.SNGL", "_xlfn."),
    ("MONTH", ""),
    ("MROUND", ""),
    ("MULTINOMIAL", ""),
    ("MUNIT", "_xlfn."),
    ("N", ""),
    ("NA", ""),
    ("NEGBINOM.DIST", "_xlfn."),
    ("NEGBINOMDIST", ""),
    ("NETWORKDAYS", ""),
    ("NETWORKDAYS.INTL", ""),
    ("NOMINAL", ""),
    ("NORM.DIST", "_xlfn."),
    ("NORM.INV", "_xlfn."),
    ("NORM.S.DIST", "_xlfn."),
    ("NORM.S.INV", "_xlfn."),
    ("NORMDIST", ""),
    ("NORMINV", ""),
    ("NORMSDIST", ""),
    ("NORMSINV", ""),
    ("NOT", ""),
    ("NOW", ""),
    ("NPER", ""),
    ("NPV", ""),
    ("NUMBERVALUE", "_xlfn."),
    ("OCT2BIN", ""),
    ("OCT2DEC", ""),
    ("OCT2HEX", ""),
    ("ODD", ""),
    ("OFFSET", ""),
    ("OR", ""),
    ("PDURATION", "_xlfn."),
    ("PEARSON", ""),
    ("PERCENTILE", ""),
    ("PERCENTILE.EXC", "_xlfn."),
    ("PERCENTILE.INC", "_xlfn."),
    ("PERCENTRANK", ""),
    ("PERCENTRANK.EXC", "_xlfn."),
    ("PERCENTRANK.INC", "_xlfn."),
    ("PERMUT", ""),
    ("PERMUTATIONA", "_xlfn."),
    ("PHI", "_xlfn."),
    ("PHONETIC", ""),
    ("PI", ""),
    ("PIVOTBY", "_xlfn."),
    ("PMT", ""),
    ("POISSON", ""),
    ("POISSON.DIST", "_xlfn."),
    ("POWER", ""),
    ("PPMT", ""),
    ("PRICE", ""),
    ("PRICEDISC", ""),
    ("PRICEMAT", ""),
    ("PROB", ""),
    ("PRODUCT", ""),
    ("PROPER", ""),
    ("PV", ""),
    ("QUARTILE", ""),
    ("QUARTILE.EXC", "_xlfn."),
    ("QUARTILE.INC", "_xlfn."),
    ("QUOTIENT", ""),
    ("RADIANS", ""),
    ("RAND", ""),
    ("RANDARRAY", "_xlfn."),
    ("RANDBETWEEN", ""),
    ("RANK", ""),
    ("RANK.AVG", "_xlfn."),
    ("RANK.EQ", "_xlfn."),
    ("RATE", ""),
    ("RECEIVED", ""),
    ("REDUCE", "_xlfn."),
    ("REGEXEXTRACT", "_xlfn."),
    ("REGEXREPLACE", "_xlfn."),
    ("REGEXTEST", "_xlfn."),
    ("REPLACE", ""),
    ("REPLACEB", ""),
    ("REPT", ""),
    ("RIGHT", ""),
    ("RIGHTB", ""),
    ("ROMAN", ""),
    ("ROUND", ""),
    ("ROUNDDOWN", ""),
    ("ROUNDUP", ""),
    ("ROW", ""),
    ("ROWS", ""),
    ("RRI", "_xlfn."),
    ("RSQ", ""),
    ("SCAN", "_xlfn."),
    ("SEARCH", ""),
    ("SEARCHB", ""),
    ("SEC", "_xlfn."),
    ("SECH", "_xlfn."),
    ("SECOND", ""),
    ("SEQUENCE", "_xlfn."),
    ("SERIESSUM", ""),
    ("SHEET", "_xlfn."),
    ("SHEETS", "_xlfn."),
    ("SIGN", ""),
    ("SIN", ""),
    ("SINH", ""),
    ("SKEW", ""),
    ("SKEW.P", "_xlfn."),
    ("SLN", ""),
    ("SLOPE", ""),
    ("SMALL", ""),
    ("SORT", "_xlfn._xlws."),
    ("SORTBY", "_xlfn."),
    ("SQRT", ""),
    ("SQRTPI", ""),
    ("STANDARDIZE", ""),
    ("STDEV", ""),
    ("STDEV.P", "_xlfn."),
    ("STDEV.S", "_xlfn."),
    ("STDEVA", ""),
    ("STDEVP", ""),
    ("STDEVPA", ""),
    ("STEYX", ""),
    ("SUBSTITUTE", ""),
    ("SUBTOTAL", ""),
    ("SUM", ""),
    ("SUMIF", ""),
    ("SUMIFS", ""),
    ("SUMPRODUCT", ""),
    ("SUMSQ", ""),
    ("SUMX2MY2", ""),
    ("SUMX2PY2", ""),
    ("SUMXMY2", ""),
    ("SWITCH", "_xlfn."),
    ("SYD", ""),
    ("T", ""),
    ("T.DIST", "_xlfn."),
    ("T.DIST.2T", "_xlfn."),
    ("T.DIST.RT", "_xlfn."),
    ("T.INV", "_xlfn."),
    ("T.INV.2T", "_xlfn."),
    ("T.TEST", "_xlfn."),
    ("TAKE", "_xlfn."),
    ("TAN", ""),
    ("TANH", ""),
    ("TBILLEQ", ""),
    ("TBILLPRICE", ""),
    ("TBILLYIELD", ""),
    ("TDIST", ""),
    ("TEXT", ""),
    ("TEXTAFTER", "_xlfn."),
    ("TEXTBEFORE", "_xlfn."),
    ("TEXTJOIN", "_xlfn."),
    ("TEXTSPLIT", "_xlfn."),
    ("TIME", ""),
    ("TIMEVALUE", ""),
    ("TINV", ""),
    ("TOCOL", "_xlfn."),
    ("TODAY", ""),
    ("TOROW", "_xlfn."),
    ("TRANSPOSE", ""),
    ("TREND", ""),
    ("TRIM", ""),
    ("TRIMMEAN", ""),
    ("TRUE", ""),
    ("TRUNC", ""),
    ("TTEST", ""),
    ("TYPE", ""),
    ("UNICHAR", "_xlfn."),
    ("UNICODE", "_xlfn."),
    ("UNIQUE", "_xlfn."),
    ("UPPER", ""),
    ("VALUE", ""),
    ("VALUETOTEXT", "_xlfn."),
    ("VAR", ""),
    ("VAR.P", "_xlfn."),
    ("VAR.S", "_xlfn."),
    ("VARA", ""),
    ("VARP", ""),
    ("VARPA", ""),
    ("VDB", ""),
    ("VLOOKUP", ""),
    ("VSTACK", "_xlfn."),
    ("WEBSERVICE", "_xlfn."),
    ("WEEKDAY", ""),
    ("WEEKNUM", ""),
    ("WEIBULL", ""),
    ("WEIBULL.DIST", "_xlfn."),
    ("WORKDAY", ""),
    ("WORKDAY.INTL", ""),
    ("WRAPCOLS", "_xlfn."),
    ("WRAPROWS", "_xlfn."),
    ("XIRR", ""),
    ("XLOOKUP", "_xlfn."),
    ("XMATCH", "_xlfn."),
    ("XNPV", ""),
    ("XOR", "_xlfn."),
    ("YEAR", ""),
    ("YEARFRAC", ""),
    ("YIELD", ""),
    ("YIELDDISC", ""),
    ("YIELDMAT", ""),
    ("Z.TEST", "_xlfn."),
    ("ZTEST", ""),
];

/// The catalog entry for a canonical name (ASCII case-insensitive, no prefix).
pub fn builtin(name: &str) -> Option<(&'static str, &'static str)> {
    BUILTINS.binary_search_by(|(n, _)| n.bytes().cmp(name.bytes().map(|b| b.to_ascii_uppercase()))).ok().and_then(|i| BUILTINS.get(i)).copied()
}

/// Whether `name` is a built-in function.
pub fn is_builtin(name: &str) -> bool {
    builtin(name).is_some()
}

/// Future functions that Excel stores with `_xlfn.` but that GridCraft does not implement, so they
/// are not built-ins: a formula that names them is kept (it evaluates to `#NAME?`) and written
/// with the prefix Excel expects.
static FILE_ONLY_FUTURE: &[&str] =
    &["FIELDVALUE", "FORECAST.ETS", "FORECAST.ETS.CONFINT", "FORECAST.ETS.SEASONALITY", "FORECAST.ETS.STAT", "IMAGE", "SINGLE"];

/// The name a file stores for a function call: `XLOOKUP` → `_xlfn.XLOOKUP`, `FILTER` →
/// `_xlfn._xlws.FILTER`; anything else unchanged.
pub fn file_name(name: &str) -> String {
    match builtin(name) {
        Some((n, prefix)) => format!("{prefix}{n}"),
        None => match FILE_ONLY_FUTURE.iter().find(|f| f.eq_ignore_ascii_case(name)) {
            Some(f) => format!("_xlfn.{f}"),
            None => name.to_string(),
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_is_sorted_and_prefixed() {
        assert!(BUILTINS.windows(2).all(|w| w[0].0 < w[1].0), "BUILTINS must be sorted and unique");
        assert_eq!(builtin("xlookup"), Some(("XLOOKUP", "_xlfn.")));
        assert_eq!(file_name("filter"), "_xlfn._xlws.FILTER");
        assert_eq!(file_name("SUM"), "SUM");
        assert_eq!(file_name("_XLUDF.MYFN"), "_XLUDF.MYFN");
        assert_eq!(file_name("NETWORKDAYS.INTL"), "NETWORKDAYS.INTL");
        assert_eq!(file_name("WORKDAY.INTL"), "WORKDAY.INTL");
        assert_eq!(file_name("forecast.ets"), "_xlfn.FORECAST.ETS");
        assert_eq!(file_name("_XLFN.FORECAST.ETS"), "_XLFN.FORECAST.ETS");
    }

    #[test]
    fn every_language_translates_the_whole_catalog() {
        for l in gridcraft_locale::LANGUAGES {
            assert_eq!(l.functions.len(), BUILTINS.len(), "{}: function table size", l.tag);
            for (name, _) in BUILTINS {
                assert!(l.local_function(name).is_some(), "{}: no local name for {name}", l.tag);
            }
        }
    }
}
